import React,{useEffect,useMemo,useState} from 'react';
import { Archive, Check, Edit3, Plus, Target, Trash2, RotateCcw, Trophy } from 'lucide-react';
import { Header } from '../components/common/Header';
import { GoalFormModal } from '../components/goals/GoalFormModal';
import { StorageService } from '../storage/db';
import type { Goal, Habit, Task, WorkoutSession } from '../types';
import { calculateGoalProgress, goalCurrentValue, goalSourceLabel } from '../utils/goalUtils';

type GoalTab='active'|'completed'|'archived';
const formatDate=(v?:string)=>{if(!v)return '';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`;};
const formatValue=(value:number,goal:Goal)=>goal.measurement==='currency'?`R$ ${value.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}`:value.toLocaleString('pt-BR');

export const GoalsPage:React.FC=()=>{
 const[goals,setGoals]=useState<Goal[]>([]);const[habits,setHabits]=useState<Habit[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[sessions,setSessions]=useState<WorkoutSession[]>([]);const[tab,setTab]=useState<GoalTab>('active');const[editing,setEditing]=useState<Goal|null>(null);const[showForm,setShowForm]=useState(false);const[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [g,h,t,s]=await Promise.all([StorageService.getGoals(),StorageService.getHabits(),StorageService.getTasks(),StorageService.getWorkoutSessions()]);const data={habits:h,tasks:t,sessions:s};const normalized=g.map(goal=>{const progress=calculateGoalProgress(goal,data);return {...goal,progress,status:progress>=100?'completed':goal.status==='completed'&&progress<100?'active':goal.status};});setGoals(normalized.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));setHabits(h);setTasks(t);setSessions(s);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const visible=useMemo(()=>goals.filter(g=>g.status===tab),[goals,tab]);
 const saveGoal=async(goal:Goal)=>{const progress=calculateGoalProgress(goal,{habits,tasks,sessions});const normalized={...goal,progress:goal.trackingSource&&goal.trackingSource!=='manual'?progress:goal.progress};await StorageService.saveGoal(normalized);await load();};
 const updateStatus=async(goal:Goal,status:Goal['status'])=>{await StorageService.saveGoal({...goal,status,progress:status==='completed'?100:goal.progress>=100?99:goal.progress});await load();};
 const removeGoal=async(goal:Goal)=>{if(!window.confirm(`Excluir a meta "${goal.title}" permanentemente?`))return;await StorageService.deleteGoalPermanently(goal.id);await load();};
 return <div className="space-y-5"><Header title="Metas" subtitle="Objetivos que acompanham sua evolução" action={<button onClick={()=>{setEditing(null);setShowForm(true);}} className="flex items-center space-x-1 px-3 py-1.5 bg-brand text-white rounded-xl text-xs font-medium shadow hover:bg-brand-hover transition-colors"><Plus size={16}/><span>Nova Meta</span></button>}/>
 <div className="bg-brand/5 border border-brand/15 rounded-2xl p-4"><div className="flex items-center gap-3"><div className="p-2.5 rounded-xl bg-brand/10 text-brand"><Target size={19}/></div><div><p className="text-sm font-semibold text-gray-100">Transforme objetivos em progresso</p><p className="text-xs text-gray-500 mt-0.5">Você pode acompanhar manualmente ou deixar o Constância contar treinos, hábitos e tarefas.</p></div></div></div>
 <div className="flex border-b border-surface-border text-xs text-gray-400 space-x-6 pb-2">{(['active','completed','archived'] as const).map(item=>{const label=item==='active'?'Ativas':item==='completed'?'Concluídas':'Arquivadas';return <button key={item} onClick={()=>setTab(item)} className={`${tab===item?'text-brand font-semibold border-b-2 border-brand':'hover:text-gray-200'} pb-2 -mb-2 transition-colors`}>{label} <span className="text-gray-600 ml-0.5">{goals.filter(g=>g.status===item).length}</span></button>;})}</div>
 {loading?<div className="py-12 text-center text-xs text-gray-500">Carregando metas...</div>:visible.length===0?<div className="border border-dashed border-surface-border rounded-2xl p-8 text-center text-gray-500 my-8 flex flex-col items-center"><Target size={32} className="text-gray-600 mb-2"/><p className="text-sm">Nenhuma meta {tab==='active'?'ativa':tab==='completed'?'concluída':'arquivada'}.</p>{tab==='active'&&<p className="text-xs mt-1 text-gray-600">Crie uma meta e deixe seu progresso aparecer por aqui.</p>}</div>:<div className="space-y-3">{visible.map(goal=>{const current=goalCurrentValue(goal,goal.progress);return <article key={goal.id} className="bg-surface-card border border-surface-border rounded-2xl overflow-hidden">{goal.imageUrl&&<img src={goal.imageUrl} alt="" className="w-full aspect-square object-cover"/>}<div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="font-semibold text-gray-100 truncate">{goal.title}</h3>{goal.status==='completed'&&<Trophy size={15} className="text-brand shrink-0"/>}</div>{goal.description&&<p className="text-xs text-gray-500 mt-1 line-clamp-2">{goal.description}</p>}</div><div className="flex items-center gap-1 shrink-0">{goal.status==='active'&&<button onClick={()=>void updateStatus(goal,'completed')} className="p-2 text-gray-500 hover:text-brand hover:bg-brand-subtle rounded-lg" title="Concluir"><Check size={16}/></button>}{(goal.status==='completed'||goal.status==='archived')&&<button onClick={()=>void updateStatus(goal,'active')} className="p-2 text-gray-500 hover:text-brand hover:bg-brand-subtle rounded-lg" title="Reativar"><RotateCcw size={16}/></button>}<button onClick={()=>{setEditing(goal);setShowForm(true);}} className="p-2 text-gray-500 hover:text-white hover:bg-surface-hover rounded-lg" title="Editar"><Edit3 size={16}/></button>{goal.status!=='archived'&&<button onClick={()=>void updateStatus(goal,'archived')} className="p-2 text-gray-500 hover:text-white hover:bg-surface-hover rounded-lg" title="Arquivar"><Archive size={16}/></button>}<button onClick={()=>void removeGoal(goal)} className="p-2 text-gray-500 hover:text-red-400 hover:bg-surface-hover rounded-lg" title="Excluir"><Trash2 size={16}/></button></div></div>
 <div className="mt-4"><div className="flex justify-between items-end text-[11px] text-gray-500 mb-1.5"><span>{goal.trackingSource&&goal.trackingSource!=='manual'?`Progresso automático · ${goalSourceLabel(goal.trackingSource)}`:'Progresso'}</span><span className="text-gray-300 font-medium">{goal.targetValue?`${formatValue(current,goal)} / ${formatValue(goal.targetValue,goal)}`:`${goal.progress}%`}</span></div><div className="h-2 bg-surface-hover rounded-full overflow-hidden"><div className="h-full bg-brand rounded-full transition-all duration-500" style={{width:`${goal.progress}%`}}/></div><div className="flex justify-between mt-1 text-[10px] text-gray-600"><span>{goal.progress}%</span>{goal.targetDate&&<span>Prazo: {formatDate(goal.targetDate)}</span>}</div></div>
 </div></article>})}</div>}
 {showForm&&<GoalFormModal goal={editing} habits={habits} onClose={()=>{setShowForm(false);setEditing(null);}} onSave={saveGoal}/>}</div>;
};
