import React,{useEffect,useMemo,useState} from 'react';
import { Archive, Check, Edit3, Plus, Target, Trash2 } from 'lucide-react';
import { Header } from '../components/common/Header';
import { GoalFormModal } from '../components/goals/GoalFormModal';
import { StorageService } from '../storage/db';
import type { Goal } from '../types';
type GoalTab='active'|'completed'|'archived';
const formatDate=(v?:string)=>{if(!v)return '';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`;};
export const GoalsPage:React.FC=()=>{const[goals,setGoals]=useState<Goal[]>([]);const[tab,setTab]=useState<GoalTab>('active');const[editing,setEditing]=useState<Goal|null>(null);const[showForm,setShowForm]=useState(false);const[loading,setLoading]=useState(true);
 const loadGoals=async()=>{setLoading(true);try{const data=await StorageService.getGoals();setGoals(data.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));}finally{setLoading(false);}};useEffect(()=>{void loadGoals();},[]);const visible=useMemo(()=>goals.filter(g=>g.status===tab),[goals,tab]);
 const saveGoal=async(goal:Goal)=>{const normalized=goal.progress>=100?{...goal,progress:100,status:'completed' as const}:goal;await StorageService.saveGoal(normalized);await loadGoals();};
 const updateStatus=async(goal:Goal,status:Goal['status'])=>{await StorageService.saveGoal({...goal,status,progress:status==='completed'?100:goal.progress});await loadGoals();};
 const removeGoal=async(goal:Goal)=>{if(!window.confirm(`Excluir a meta "${goal.title}" permanentemente?`))return;await StorageService.deleteGoalPermanently(goal.id);await loadGoals();};
 return <div className="space-y-5"><Header title="Metas" subtitle="Objetivos de curto e longo prazo" action={<button onClick={()=>{setEditing(null);setShowForm(true);}} className="flex items-center space-x-1 px-3 py-1.5 bg-brand text-white rounded-xl text-xs font-medium shadow hover:bg-brand-hover transition-colors"><Plus size={16}/><span>Nova Meta</span></button>}/><div className="flex border-b border-surface-border text-xs text-gray-400 space-x-6 pb-2">{(['active','completed','archived'] as const).map(item=>{const label=item==='active'?'Ativas':item==='completed'?'Concluídas':'Arquivadas';return <button key={item} onClick={()=>setTab(item)} className={`${tab===item?'text-brand font-semibold border-b-2 border-brand':'hover:text-gray-200'} pb-2 -mb-2 transition-colors`}>{label} <span className="text-gray-600 ml-0.5">{goals.filter(g=>g.status===item).length}</span></button>;})}</div>
 {loading?<div className="py-12 text-center text-xs text-gray-500">Carregando metas...</div>:visible.length===0?<div className="border border-dashed border-surface-border rounded-2xl p-8 text-center text-gray-500 my-8 flex flex-col items-center"><Target size={32} className="text-gray-600 mb-2"/><p className="text-sm">Nenhuma meta {tab==='active'?'ativa':tab==='completed'?'concluída':'arquivada'}.</p>{tab==='active'&&<p className="text-xs mt-1 text-gray-600">Crie uma meta e acompanhe seu progresso.</p>}</div>:<div className="space-y-3">{visible.map(goal=><article key={goal.id} className="bg-surface-card border border-surface-border rounded-2xl overflow-hidden group">{goal.imageUrl&&<img src={goal.imageUrl} alt="" className="w-full aspect-square object-cover"/>}<div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-semibold text-gray-100 truncate">{goal.title}</h3>{goal.description&&<p className="text-xs text-gray-500 mt-1 line-clamp-2">{goal.description}</p>}</div><div className="flex items-center gap-1 shrink-0">{goal.status==='active'&&<button onClick={()=>void updateStatus(goal,'completed')} className="p-2 text-gray-500 hover:text-brand hover:bg-brand-subtle rounded-lg" title="Concluir"><Check size={16}/></button>}<button onClick={()=>{setEditing(goal);setShowForm(true);}} className="p-2 text-gray-500 hover:text-white hover:bg-surface-hover rounded-lg" title="Editar"><Edit3 size={16}/></button>{goal.status!=='archived'&&<button onClick={()=>void updateStatus(goal,'archived')} className="p-2 text-gray-500 hover:text-white hover:bg-surface-hover rounded-lg" title="Arquivar"><Archive size={16}/></button>}<button onClick={()=>void removeGoal(goal)} className="p-2 text-gray-500 hover:text-red-400 hover:bg-surface-hover rounded-lg" title="Excluir"><Trash2 size={16}/></button></div></div><div className="mt-4"><div className="flex justify-between text-[11px] text-gray-500 mb-1.5"><span>Progresso</span><span>{goal.progress}%</span></div><div className="h-1.5 bg-surface-hover rounded-full overflow-hidden"><div className="h-full bg-brand rounded-full transition-all duration-500" style={{width:`${goal.progress}%`}}/></div></div>{goal.targetDate&&<p className="text-[11px] text-gray-600 mt-3">Prazo: {formatDate(goal.targetDate)}</p>}</div></article>)}</div>}
 {showForm&&<GoalFormModal goal={editing} onClose={()=>{setShowForm(false);setEditing(null);}} onSave={saveGoal}/>}</div>;};
